name: Metrics
on:
  schedule: 
    - cron: "0 12 * * *"
  workflow_dispatch:
  push: 
    branches: ["main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    # ✅ IMPORTANT: Permissions explicites
    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: AyGoub
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Paris
          filename: github-metrics.svg
          
          # Configuration languages
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%