name: Mirror TryHackMe badge

on:
  schedule:
    - cron: "0 5 * * *"   # tous les jours à 05:00 UTC
  workflow_dispatch:       # lancer manuellement si besoin

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          ref: main       # ⚠️ mets master si ta branche par défaut s'appelle master
          fetch-depth: 0

      - name: Download current badge from TryHackMe
        run: |
          mkdir -p .github/tmp
          curl -fsSL "https://tryhackme-badges.s3.amazonaws.com/AyGoub.png" -o .github/tmp/thm-badge.png
          if [ ! -s .github/tmp/thm-badge.png ]; then
            echo "Badge download failed or is empty."
            exit 1
          fi

      - name: Replace local image only if changed
        run: |
          if [ -f thm-badge.png ]; then
            if cmp -s thm-badge.png .github/tmp/thm-badge.png; then
              echo "No change in badge image."
              exit 0
            fi
          fi
          mv .github/tmp/thm-badge.png thm-badge.png

      - name: Commit updated badge
        run: |
          if git diff --quiet; then
            echo "Nothing to commit."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add thm-badge.png
          git commit -m "chore: update TryHackMe badge"
          git push
